Bootstrap upgrade
SPANDigital/presidium-styling-base pull request #8
Opened 2024-12-04 08:06 UTC by julianbyte

## Description
Bootstrap upgrade

## Issue
- [PRSDM-6979](https://spandigital.atlassian.net/browse/PRSDM-6979)

## Screenshots

## PR Readiness Checks
- [ ] Your PR title conforms to conventional commits `<type>: <jira-ticket-num><title>`, for example: `fix: PRSDM-123 issue with login` with a maximum of 100 characters
- [ ] You have performed a self-review of your changes via the GitHub UI
- [ ] Comments were added to new code that can not explain itself (see [reference 1](https://bpoplauschi.github.io/2021/01/20/Clean-Code-Comments-by-Uncle-Bob-part-2.html) and [reference 2](https://blog.cleancoder.com/uncle-bob/2017/02/23/NecessaryComments.html))
- [ ] New code adheres to the following quality standards:
  - Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
  - Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
  - DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
  - YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))

2024-12-10 11:39 UTC, Quantumplate requested changes
@julianbyte Great work so far!
Please make sure to check the functionality on both SPAN Handbook & Presidium Docs Internal. 
Please investigate why the default expand on click isn't working in the left nav 👍🏼 
As discussed here https://spandigital.slack.com/archives/C011F59S9QE/p1733820430309659

2024-12-20 06:02 UTC, CharlRitterDev approved these changes

2025-01-14 12:58 UTC, Quantumplate reviewed
@julianbyte I'm still having problems getting this to work locally.
Please could we work through it tomorrow together?

2025-03-10 13:58 UTC, Quantumplate commented
stale PR

2025-03-10 13:58 UTC, closed without merging